### ISSUE TITLE
opencred with CA DMV wallet UI; local network setup

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [stateofca/opencred#5]
Hi folks :)

(tagging @mattcollier @kezike @ottonomy https://github.com/tmarkovski from the previous issue)

Aim: I have been working on getting opencreds up locally and using my CA DMV wallet to share mDL and verify it.

> Note: Happy to contribute this to the repo so that we don't need to open ports to local machines globally. I was warned not to open ports to my machine due to security concerns.

The phone wallet communicates with the opencred endpoints, but the Credential selection UI on the wallet and then subsequent transfer doesn't take place.

Setup:
1. Dev machine and phone with wallet should be on the same local network. Get the `en0` ip after `ifconfig`
2. Use that ip in the `config.example.yaml` section `baseUri: http://<ip>:<port>` port set in the app is 22080
3. Generate signing keys `opencred git:(main) ✗ npm run generate:prime256v1 id_token authorization_request vp_token` and paste in `config.example.yaml`
4. did config in `config.example.yaml`
```
    didWeb:
      mainEnabled: true
```
<details>
  <summary>config.example.yaml</summary>
    ```
    app:
      server:
        baseUri: http://<en0 ip>:22080
      opencred:
        caStore:
          - pem: |
              -----BEGIN CERTIFICATE-----
              <VALID CERTIFICATE>
              -----END CERTIFICATE-----
        signingKeys:
        - type: ES256
          id: 2eb917931c154afc45c6b3c9f3dacc01a4cc60b6a4c1a8bb4a4ec0f7aa2d3a66
          privateKeyPem: <generated above>
          publicKeyPem: <generated above>
          purpose:
            - id_token
            - authorization_request
            - vp_token
        relyingParties:
          - name: "Test Relying Party (Native)"
            clientId: "rp1"
            clientSecret: "DeepestAndDarkest"
            description: "Relying Party Test App"
            primaryLogo: "https://placekitten.com/200/200"
            primaryLink: "https://example.com"
            secondaryLogo: "https://placekitten.com/200/200"
            secondaryLink: "https://example2.com"
            homeLink: "https://example.com"
            explainerVideo:
              id: "<YOUTUBE ID>"
              provider: youtube
            backgroundImage: "https://placekitten.com/800/200"
            redirectUri: "http://localhost:3000"
            idTokenExpirySeconds: 3600
            claims:
              - name: "dl_number"
                path: "driversLicense.document_number"
            brand:
              cta: "#0B669D"
              primary: "#045199"
              header: "#0979c4"
            scopes:
              - name: "openid"
                description: "Open ID Connect"
            workflow:
              type: native
              id: z1A32xJZGqBeAEcMq56avmw2L
              initialStep: default
              steps:
                default:
                  createChallenge: true
                  verifiablePresentationRequest: >
                    {
                      "query": {
                        "type": "QueryByExample",
                        "credentialQuery": {
                          "reason": "Please present your VC.",
                          "example": {
                            "type": [
                              "Iso18013DriversLicenseCredential"
                            ]
                          }
                        }
                      }
                    }
                  constraintsOverride: >
                    {
                      "fields": [
                        {
                          "path": [
                            "$.vc.type"
                          ],
                          "filter": {
                            "type": "string",
                            "pattern": "Iso18013DriversLicenseCredential"
                          }
                        }
                      ]
                    }
        options:
          exchangeProtocols:
            - chapi
            - openid4vp
        defaultBrand:
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        enableAudit: true
        auditFields:
          - type: text
            id: given_name
            name: First Name
            path: "$.credentialSubject.given_name"
            required: true
          - type: text
            id: family_name
            name: Last Name
            path: "$.credentialSubject.family_name"
            required: false
          - type: date
            id: birth_date
            name: Date of Birth
            path: "$.credentialSubject.birth_date"
            required: true
        defaultLanguage: en
        translations:
          en:
            qrTitle: Login with your Wallet app
            qrPageExplain: Scan the following QR Code using the Wallet app on your phone.
            qrPageExplainHelp: (<a href="https://youtube.com">How do I do it?</a>)
            qrFooter: "Note: Already on your phone with the Wallet app? Open the Wallet app, then come back and tap on the QR code above."
            qrFooterHelp: Difficulty using the Wallet app to login? revert to using password <a href="#">here</a>
            qrDisclaimer: If you don't have a Wallet app download it from the app store.
            qrExplainerText: (How do I do it?)
            qrPageAnotherWay: Want to try another way?
            chapiPageAnotherWay: "Looking for a QR Code to scan with you wallet app instead?"
            loginCta: "Login with your credential wallet"
            loginExplain: "To login with your credential wallet, you will need to have the credential wallet app <with configurable URL to app stores> installed"
            appInstallExplain: "If you don't have a credential wallet yet, you can get one by downloading the credential wallet app <with configurable URL to app stores>"
            appCta: "Open wallet app"
            copyright: "Powered by OpenCred"
            pageTitle: "Login"
            home: "Home"
        didWeb:
          mainEnabled: true
      ```
</details>

5. `mkdir /etc/bedrock-config; cd opencreds; cp configs/config.example.yaml /etc/bedrock-config/combined.yaml`

6.`npm start` build and bring up the service

7.1 Use `http://0.0.0.0:22080/.well-known/did.json` to see the published `did:web`
```
{
  "@context": [
    "https://www.w3.org/ns/did/v1"
  ],
  "id": "did:web:192.168.1.101:22080",
  "verificationMethod": [
    {
      "id": "did:web:192.168.1.101:22080#2eb917931c154afc45c6b3c9f3dacc01a4cc60b6a4c1a8bb4a4ec0f7aa2d3a66",
      "controller": "did:web:192.168.1.101:22080",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "x": "NFFfW7wohPR_ttv3DbSZpJVM-aD3eGf9YCYZQkwv4jU",
        "y": "QETxN1LCd7YMDctxfuaMX3NsGklf8SeYuCVLbDITxbM",
        "crv": "P-256"
      }
    }
  ],
  "assertionMethod": [
    "did:web:192.168.1.101:22080#2eb917931c154afc45c6b3c9f3dacc01a4cc60b6a4c1a8bb4a4ec0f7aa2d3a66"
  ]
}
```
7.2 use `http://0.0.0.0:22080/api-docs/#/OIDC/OpenID%20Connect%20Login` with the correct `client_id` and `redirect_uri` as specified in the `config.example.yaml`
8. connect to mongodb `mongosh mongodb://localhost:27017/opencred_localhost`
8.1 
```
opencred_localhost> db.Exchanges.find().pretty()
[
  {
    _id: ObjectId('6670c00e9116e372413d55c8'),
    id: 'z1ABpbVvGcJaDDW68seuk5vi1',
    workflowId: 'z1A32xJZGqBeAEcMq56avmw2L',
    sequence: 0,
    ttl: 900,
    state: 'pending',
    variables: {},
    step: 'default',
    challenge: 'z1AEgLn9VNyW1T5pFqXnuNYK2',
    accessToken: 'z1A5uUiyTn7PP45isgE58QzPZ',
    createdAt: ISODate('2024-06-17T23:00:30.093Z'),
    recordExpiresAt: ISODate('2024-06-18T23:15:30.093Z'),
    oidc: { code: null, state: '' }
  }
]
```
9. use https://www.onlinewebtoolkit.com/base64-to-image-converter and paste the base 64 that you get in the above used swagger api `"QR": "data:image/png;base64,...`. This generates the QR code.
10. Scan the QR code
10.1 It looks like this
<img src="https://github.com/stateofca/opencred/assets/17696886/81302a06-de59-416f-a51a-2aac28bbfb04" alt="QR-code" width="200"/>

10.2 Translates to this
```
openid4vp://?client_id=did:web:192.168.1.101:22080&request_uri=http://192.168.1.101:22080/workflows/z1A32xJZGqBeAEcMq56avmw2L/exchanges/z1ABpbVvGcJaDDW68seuk5vi1/openid/client/authorization/request
```
10. You can either scan and continue or take the above and use curl on the request_uri from phone (using curl in terminal) gives you this:
<img src="https://github.com/stateofca/opencred/assets/17696886/322a5c4f-9530-4699-a887-155611b04b6f" alt="terminal" width="200"/>

11. and use the mongodb interface to see the updated exchange object:
```
opencred_localhost> db.Exchanges.find().pretty()
[
  {
    _id: ObjectId('6670c00e9116e372413d55c8'),
    id: 'z1ABpbVvGcJaDDW68seuk5vi1',
    workflowId: 'z1A32xJZGqBeAEcMq56avmw2L',
    sequence: 0,
    ttl: 900,
    state: 'pending',
    variables: {
      authorizationRequest: {
        response_type: 'vp_token',
        response_mode: 'direct_post',
        presentation_definition: {
          id: 'c6f127dc-33d6-47f3-8bcf-d196196866b5',
          input_descriptors: [
            {
              id: '0a6dd448-8dd1-494a-b2ef-938e56583d43',
              constraints: {
                fields: [
                  {
                    path: [ '$.vc.type' ],
                    filter: {
                      type: 'string',
                      pattern: 'Iso18013DriversLicenseCredential'
                    }
                  }
                ]
              },
              purpose: 'Please present your VC.',
              format: { jwt_vc_json: { alg: [ 'ES256' ] } }
            }
          ]
        },
        client_id: 'did:web:192.168.1.101:22080',
        client_id_scheme: 'did',
        nonce: 'z1AEgLn9VNyW1T5pFqXnuNYK2',
        response_uri: 'http://192.168.1.101:22080/workflows/z1A32xJZGqBeAEcMq56avmw2L/exchanges/z1ABpbVvGcJaDDW68seuk5vi1/openid/client/authorization/response',
        state: 'z1A4BrUYWyprc4HMGBEKR5kBi',
        client_metadata: {
          client_name: 'OpenCred Verifier',
          subject_syntax_types_supported: [ 'did:jwk' ],
          vp_formats: { jwt_vc: { alg: [ 'ES256' ] } }
        }
      }
    },
    step: 'default',
    challenge: 'z1AEgLn9VNyW1T5pFqXnuNYK2',
    accessToken: 'z1A5uUiyTn7PP45isgE58QzPZ',
    createdAt: ISODate('2024-06-17T23:00:30.093Z'),
    recordExpiresAt: ISODate('2024-06-18T23:15:30.093Z'),
    oidc: { code: null, state: '' },
    updatedAt: ISODate('2024-06-17T23:01:57.523Z')
  }
]
```

But the CA DMV app UI doesn't do anything, i also tried using the "Scan Website QR Code" To share online.
Am i missing something? I don't have anything on `http://locathost:3000` is that the issue?
